### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [RuedigerMoeller/kontraktor#14]
Is it possible to relicense under ASL 2.0

**Comment by RuedigerMoeller** [comment]
Why ?

**Comment by sirinath** [comment]
1. Many legal departments do not allow LGPL dependencies
2. This is not compatible with ASL 2.0 to combine with works to be distributed under ASL 2.0

**Comment by RuedigerMoeller** [comment]
1. Hm .. I think they can't use it then or have to ask for a dedicated license
2. Are yous sure ? AFAIK if one has a LGPL as a dependent jar, this is not not a problem. I will investigate ..

**Comment by sirinath** [comment]
I think LGP 2.1 was less strict but it become stricter. I do not thing you can use tools like ProGuad regardless of whatever version of LGPL.

**Comment by RuedigerMoeller** [comment]
See, at least there must be some advantage for me providing open source libraries. It's personal exposure which (might) help me getting into high-profile, challenging projects (beyond random .jsp inhouse app's). 
I cannot see any value for me if users/customers include my libraries in an invincible, obfuscated way, without even mentioning my project.
Ofc course its possible to make dedicated per-client licensing relaxing the limits. These must then be negotiated on a case by case base.
To avoid technical limits: the android client is ASL 2.0 (because of android app deployment mechanics) and the javascript client is ASL (minification,aggregation possible). The core kontraktor framework runs on server side anyway, so no point to obfuscate it there.

**Comment by sirinath** [comment]
ProGuard is to optimise the code thought it can obfuscate also.

**Comment by RuedigerMoeller** [comment]
Well you have to limit proguard on your application then, sorry

**Comment by sirinath** [comment]
Maybe this license might mitigated your worries: https://en.wikipedia.org/wiki/Zlib_License

**Comment by RuedigerMoeller** [comment]
Thanks for the input, I'll have a look into that :).

2015-08-11 5:37 GMT+02:00 Suminda Dharmasena notifications@github.com:
