### ISSUE TITLE
Native React support!

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#47]
You have been busy! Our front end is React. We are currently using js4k from V3.33 for our interface to the back end. We started using node.js to serve the compiled React components, but switched to nginx to eliminate the use of a daemon, as used by nodejs.

What are the advantages of using the native React support in 4.0?

**Comment by RuedigerMoeller** [comment]
basically, I am trying to ease react development using a java service (no need for daemon etc.). While using nginx to avoid use of a daemon , its still a lot of mess for a react starter, I just want to eliminate it.
(Kontraktor-web starts a babel-daemon behind the scenes in order to ease things.)

Main issue for making a 4.0 release is overall consolidation (got stuck with old fst due to 160GB of serialized persisted data etc..) . I also want to improve documentation and samples as well as improve javascript interop (mix nodjs and java written services etc.).

Another issue I'd like to address is to provide all the must-have webapp stuff like session invalidation, session resurrection, login + register in a smallish web framework (kontraktor-web). 

I also rewrote the js client now using a proper es6 replacement instead of somewhat messy js4k (my first piece of javascript >20 lines ;) )

Its still in the making ...

**Comment by davidwynter** [comment]
Great news on the must-have webapp stuff.... Will take a while to get my head around the migration from 3.33 to 4.0

**Comment by RuedigerMoeller** [comment]
don't do it !! 
At least not yet. I haven't migrated my commercial codebase myself. I am basically moving reusable stuff from application to kontraktor. Also made some renamings =)

**Comment by davidwynter** [comment]
Yeah, was only planning at this stage, let me know when you think it is feasible.

**Comment by RuedigerMoeller** [comment]
with 4.07 there is a java implemented jsx transpiler, so no babel/node required anymore if its feasible to rely on basic browser es6 support (classes, arrow functions) for a project.
